### ISSUE TITLE
Syntax error on import

### ISSUE THREAD

**Issue by Cleanchristian** [rili-live/react-native-phone-input#11]
I get this mistake when importing to a React file: 

./node_modules/@react-native-picker/picker/js/Picker.web.js
SyntaxError: .../node_modules/@react-native-picker/picker/js/Picker.web.js: Unexpected token (10:12)

   8 | import * as React from 'react';
   9 | import {forwardRef, useRef} from 'react';
> 10 | import type {ViewProps} from 'react-native-web/src/exports/View/types';
     |             ^
  11 | import type {GenericStyleProp} from 'react-native-web/src/types';
  12 | import type {TextStyle} from 'react-native-web/src/exports/Text/types';

**Comment by rililive** [comment]
This is related to your environment configuration and not related to this package
