### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCPicker

### ISSUE THREAD

**Issue by dkunin9** [rili-live/react-native-phone-input#12]
Hello! 
Facing this issue with your fork repo and the original one.. 
**Invariant Violation: Tried to register two views with the same name RNCPicker**

P.s. I'm not using `native-base` or any other library with `@react-native-picker/picker`
version in package.json:
`"@react-native-picker/picker": "^1.9.10",`
    
Have tried also this one in CountryPicker.tsx
`import {Picker as CustomPicker} from '@react-native-picker/picker';`

Thank you in advance

**Comment by rililive** [comment]
See the pinned issue https://github.com/rili-live/react-native-phone-input/issues/5
