### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Tesla-Renting** [rili-live/react-native-phone-input#17]
### Steps to reproduce
`expo install react-native-phone-input` (`yarn add react-native-phone-input`

### Result
There is a deprecation warning.
```
(node:5836) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by rililive** [comment]
This warning comes from dependencies of the project which is a non-issue for the foreseeable future
