### ISSUE TITLE
Package is just not working anymore

### ISSUE THREAD

**Issue by metchegarayhw** [rili-live/react-native-phone-input#34]
<img width="1305" alt="Capture d’écran 2022-04-06 à 10 44 05" src="https://user-images.githubusercontent.com/82954157/161934306-9aeb98ed-cd57-41a8-94b6-f852f1117e07.png">

**Comment by rililive** [comment]
Did you install `@react-native-picker/picker`?

**Comment by devin989** [comment]
Install `@react-native-picker/picker`. It will be resolved.
