### ISSUE TITLE
Kazakhstan number

### ISSUE THREAD

**Issue by Zakyyy** [rili-live/react-native-phone-input#36]
I am trying to write a Kazakhstan number +77019883584 also I have allowZeroAfterCountryCode set to false
the 0 after +77 is removed because the country in the countries list has a country code of +77 and it should be only +7

check the image for reference 
<img width="1456" alt="Screen Shot 2022-05-10 at 3 04 44 PM" src="https://user-images.githubusercontent.com/25394763/167634993-ec90337a-a7d0-4ad4-a28c-fa76304aa5ad.png">

**Comment by zizzle6717** [comment]
Please make a PR to fix, and I will merge and publish the updated version.

**Comment by Zakyyy** [comment]
here is the pr 
https://github.com/thegamenicorus/react-native-phone-input/pull/164
@zizzle6717

**Comment by rililive** [comment]
Please make a pull request here https://github.com/rili-live/react-native-phone-input/pulls

**Comment by Zakyyy** [comment]
@rililive done
