### ISSUE TITLE
Tried to register two views with the same name RNCAndroidDropdownPicker

### ISSUE THREAD

**Issue by Goowwy** [rili-live/react-native-phone-input#5]
Invariant Violation: Tried to register two views with the same name RNCAndroidDropdownPicker

how can i solve it?

**Comment by zizzle6717** [comment]
Try renaming the picker you are importing. For example `import CountryPicker, { CountryCode } from 'react-native-country-picker-modal';` https://stackoverflow.com/questions/65466440/invariant-violation-tried-to-register-two-views-with-the-same-name-rncandroiddr

**Comment by rililive** [comment]
Closed and pinned for future reference

**Comment by PTBYSR** [comment]
> [Goowwy](/Goowwy)

Were you able to get it fixed? I'm getting the same problem

**Comment by ycldz** [comment]
Can you tell me if you have found a solution?
